name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Ensure all modifiers have withTestTag
        run: |
          if grep -r "modifier = Modifier" ./app/src/main | grep -v "withTestTag"; then
            echo "Found a modifier without withTestTag!"
            exit 1
          fi

      - name: Build project
        run: ./gradlew buil

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*